### ISSUE TITLE
CSP preventing LNC from working

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#1312]
https://stacker.news/items/653374?commentId=653466

**Comment by huumn** [comment]
It might be safe to add [wasm-unsafe-eval](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#unsafe_webassembly_execution) considering all of other CSP stuff will prevent scripts that aren't ours from running?

**Comment by ekzyis** [comment]
I tried to get the prod build running locally to test if I can reproduce the issue. During development, we always use `unsafe-eval` because the dev build requires it for hot reload. This means that LNC might never have worked in prod but only locally thanks to `unsafe-eval`.

I unset `grpc_proxy` in .env.production, started required containers with `sndev start db sn_lnd` and then ran `npm run build && PORT=3000 npm start` but I got this error:

```
ApolloError: Cannot read properties of undefined (reading 'length')
    at new ApolloError (/home/ekzyis/prog/stacker.news/node_modules/@apollo/client/errors/errors.cjs:33:28)
    at /home/ekzyis/prog/stacker.news/node_modules/@apollo/client/core/core.cjs:1999:47
    at both (/home/ekzyis/prog/stacker.news/node_modules/@apollo/client/utilities/utilities.cjs:1347:31)
    at /home/ekzyis/prog/stacker.news/node_modules/@apollo/client/utilities/utilities.cjs:1338:72
    at new Promise (<anonymous>)
    at Object.then (/home/ekzyis/prog/stacker.news/node_modules/@apollo/client/utilities/utilities.cjs:1338:24)
    at Object.next (/home/ekzyis/prog/stacker.news/node_modules/@apollo/client/utilities/utilities.cjs:1349:49)
    at notifySubscription (/home/ekzyis/prog/stacker.news/node_modules/zen-observable/lib/Observable.js:135:18)
    at onNotify (/home/ekzyis/prog/stacker.news/node_modules/zen-observable/lib/Observable.js:179:3)
    at SubscriptionObserver.next (/home/ekzyis/prog/stacker.news/node_modules/zen-observable/lib/Observable.js:235:7) {
  graphQLErrors: [
    TypeError: Cannot read properties of undefined (reading 'length')
        at om (/home/ekzyis/prog/stacker.news/node_modules/@prisma/client/runtime/library.js:121:5438)
        at bl (/home/ekzyis/prog/stacker.news/node_modules/@prisma/client/runtime/library.js:121:5244)
        at _n.unpack (/home/ekzyis/prog/stacker.news/node_modules/@prisma/client/runtime/library.js:121:8476)
        at _n.mapQueryEngineResult (/home/ekzyis/prog/stacker.news/node_modules/@prisma/client/runtime/library.js:121:6943)
        at Object.singleLoader (/home/ekzyis/prog/stacker.news/node_modules/@prisma/client/runtime/library.js:121:6361)
        at async _n.request (/home/ekzyis/prog/stacker.news/node_modules/@prisma/client/runtime/library.js:121:6628)
        at async l (/home/ekzyis/prog/stacker.news/node_modules/@prisma/client/runtime/library.js:130:9355)
        at async itemQueryWithMeta (/home/ekzyis/prog/stacker.news/.next/server/chunks/7648.js:2119:19)
        at async Object.items (/home/ekzyis/prog/stacker.news/.next/server/chunks/7648.js:2160:93)
        at async Promise.all (index 1) {
      path: [Array],
      locations: undefined,
      extensions: [Object: null prototype] {}
    }
  ],
  protocolErrors: [],
  clientErrors: [],
  networkError: null,
  extraInfo: undefined
}
```

Apparently, `itemQueryWithMeta` triggers it but no idea which line exactly.

Reading [what MDN has to say about `unsafe-wasm-eval`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#unsafe_webassembly_execution), I also think it's safe to add it:

> The `'wasm-unsafe-eval'` source expression controls WebAssembly execution. If a page has a CSP header and `'wasm-unsafe-eval'` isn't specified in the `script-src` directive, WebAssembly is blocked from loading and executing on the page.
>
> The `'wasm-unsafe-eval'` source expression is more specific than `'unsafe-eval'` which permits both compilation (and instantiation) of WebAssembly and, for example, the use of the `eval` operation in JavaScript. If the `'unsafe-eval'` source keyword is used, then this overrides any occurrence of `'wasm-unsafe-eval'` in the CSP policy.
