### ISSUE TITLE
Firefox mobile logout not working

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#1332]
Received a report that logging out in Firefox mobile is ineffective.

**Comment by ekzyis** [comment]
Was able to reproduce on iOS. If you hit the logout button, nothing happens.

I think it's related to these CSP errors on Firefox desktop:

```
Content-Security-Policy warnings 4
Content-Security-Policy: Ignoring “'self'” within script-src: ‘strict-dynamic’ specified [stacker.news](https://stacker.news/)
Content-Security-Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified [stacker.news](https://stacker.news/) [stacker.news]
Content-Security-Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified [stacker.news](https://stacker.news/)
Content-Security-Policy: Ignoring “'unsafe-inline'” within script-src: nonce-source or hash-source specified
Content-Security-Policy: The page’s settings blocked a JavaScript eval (script-src) from being executed because it violates the following directive: “script-src 'self' 'unsafe-inline' 'wasm-unsafe-eval' 'nonce-M2EwZmQ0NDQtMTcwZS00ZDJhLTljZjAtZmYxN2Y1MTM0Nzlh' 'strict-dynamic' https:” (Missing 'unsafe-eval') 2 [index.js:12](webpack://_N_E/node_modules/@protobufjs/inquire/index.js)
Content-Security-Policy: The page’s settings blocked the loading of a resource (default-src) at https://a.stacker.news/_next/static/chunks/pages/search-be04387d83a90549.js because it violates the following directive: “default-src 'none'” [route-loader.js:98:22](webpack://_N_E/node_modules/next/dist/client/route-loader.js)
Content-Security-Policy: The page’s settings blocked the loading of a resource (default-src) at https://a.stacker.news/_next/static/chunks/pages/~/recent-9dedf4def2e51735.js because it violates the following directive: “default-src 'none'” [route-loader.js:98:22](webpack://_N_E/node_modules/next/dist/client/route-loader.js)
Content-Security-Policy: The page’s settings blocked the loading of a resource (default-src) at https://a.stacker.news/_next/static/chunks/pages/~/random-ba62fd8a6135ed0f.js because it violates the following directive: “default-src 'none'” [route-loader.js:98:22](webpack://_N_E/node_modules/next/dist/client/route-loader.js)
Content-Security-Policy: The page’s settings blocked the loading of a resource (default-src) at https://a.stacker.news/_next/static/chunks/pages/~/post-d6883e94283e76a5.js because it violates the following directive: “default-src 'none'” [route-loader.js:98:22](webpack://_N_E/node_modules/next/dist/client/route-loader.js)
Content-Security-Policy: The page’s settings blocked the loading of a resource (default-src) at https://a.stacker.news/_next/static/chunks/pages/~/top/%5Btype%5D/%5Bwhen%5D-22b98254216d53cb.js because it violates the following directive: “default-src 'none'” [route-loader.js:98:22](webpack://_N_E/node_modules/next/dist/client/route-loader.js)
Content-Security-Policy: The page’s settings blocked the loading of a resource (default-src) at https://a.stacker.news/_next/static/chunks/pages/items/%5Bid%5D-0a5686dcaaa626b0.js because it violates the following directive: “default-src 'none'” [route-loader.js:98:22](webpack://_N_E/node_modules/next/dist/client/route-loader.js)
Content-Security-Policy: The page’s settings blocked the loading of a resource (default-src) at https://a.stacker.news/_next/static/chunks/pages/%5Bname%5D-8b32b03d827abb23.js because it violates the following directive: “default-src 'none'” [route-loader.js:98:22](webpack://_N_E/node_modules/next/dist/client/route-loader.js)
Content-Security-Policy: The page’s settings blocked the loading of a resource (default-src) at https://a.stacker.news/_next/static/chunks/pages/~/recent/%5Btype%5D-1b9a62208bdbaeef.js because it violates the following directive: “default-src 'none'” [route-loader.js:98:22](webpack://_N_E/node_modules/next/dist/client/route-loader.js)
Content-Security-Policy: The page’s settings blocked the loading of a resource (default-src) at https://a.stacker.news/_next/static/chunks/pages/rewards-6084c48b31015d6a.js because it violates the following directive: “default-src 'none'” [route-loader.js:98:22](webpack://_N_E/node_modules/next/dist/client/route-loader.js)
Content-Security-Policy: The page’s settings blocked the loading of a resource (default-src) at https://a.stacker.news/_next/static/chunks/pages/stackers/%5Bwhen%5D-868292d7bcb5ad70.js because it violates the following directive: “default-src 'none'” [route-loader.js:98:22](webpack://_N_E/node_modules/next/dist/client/route-loader.js)
```

Solution is probably this patch:

```diff
diff --git a/middleware.js b/middleware.js
index b25c6ec5..b9b12945 100644
--- a/middleware.js
+++ b/middleware.js
@@ -91,7 +91,7 @@ export function middleware (request) {
     // Using nonces and strict-dynamic deploys a strict CSP.
     // see https://cheatsheetseries.owasp.org/cheatsheets/Content_Security_Policy_Cheat_Sheet.html#strict-policy.
     // Old browsers will ignore nonce and strict-dynamic and fallback to host-based matching and unsafe-inline
-    `script-src 'self' 'unsafe-inline' 'wasm-unsafe-eval' 'nonce-${nonce}' 'strict-dynamic' https:` + devScriptSrc,
+    `script-src 'self' a.stacker.news 'unsafe-inline' 'wasm-unsafe-eval' 'nonce-${nonce}' 'strict-dynamic' https:` + devScriptSrc,
     // unsafe-inline for styles is not ideal but okay if script-src is using nonces
     "style-src 'self' a.stacker.news 'unsafe-inline'",
     "manifest-src 'self'",
```

But I will investigate why they only happen on Firefox but not in Chrome or Safari.

**Comment by ekzyis** [comment]
Will close this after I tested

**Comment by ekzyis** [comment]
Mhh, the CSP errors still show up in Firefox. It really wants to have `a.stacker.news` in `default-src`.

I looked at the violating code a little closer. It creates a `<link rel="prefetch">` element. It seems like Firefox does not use `script-src` for `<link rel="prefetch">` unlike the other browsers. [This bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1242902) from 8 years ago seems related. I can still reproduce the CSP errors in Firefox with the included link but they also show up in Chrome unlike in our case :thinking:. The discussion mentions however that Chromium is exempt so sounds like our case. The discussion seems to have continued [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1457204) (last comment 8 months ago).

I'll just add `default-src 'self' a.stacker.news` to our CSP. I just find this CSP stuff very interesting.

**Comment by ekzyis** [comment]
Confirmed that it's working now
