### ISSUE TITLE
estimateRouteFee usage broken in master branch?

### ISSUE THREAD

**Issue by riccardobl** [stackernews/stacker.news#1482]
p2p zaps fails in master branch with this error
```
app  |   failed to create stacker invoice, falling back to SN invoice Error: 2 UNKNOWN: invalid length destination key
app  |       at callErrorFromStatus (/app/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
app  |       at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client.js:193:76)
app  |       at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)
app  |       at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
app  |       at /app/node_modules/@grpc/grpc-js/build/src/resolving-call.js:129:78
app  |       at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
app  |   for call at
app  |       at ServiceClientImpl.makeUnaryRequest (/app/node_modules/@grpc/grpc-js/build/src/client.js:161:32)
app  |       at ServiceClientImpl.<anonymous> (/app/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
app  |       at eval (webpack-internal:///(api)/./api/lnd/index.js:47:20)
app  |       at new Promise (<anonymous>)
app  |       at estimateRouteFee (webpack-internal:///(api)/./api/lnd/index.js:38:18)
app  |       at wrapInvoice (webpack-internal:///(api)/./wallets/wrap.js:136:115)
app  |       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
app  |       at async createLightningInvoice (webpack-internal:///(api)/./api/paidAction/index.js:266:57)
app  |       at async performOptimisticAction (webpack-internal:///(api)/./api/paidAction/index.js:150:25)
app  |       at async performPaidAction (webpack-internal:///(api)/./api/paidAction/index.js:106:20)
app  |       at async Object.act (webpack-internal:///(api)/./api/resolvers/item.js:1134:24) {
app  |     code: 2,
app  |     details: 'invalid length destination key',
app  |     metadata: Metadata {
app  |       internalRepr: Map(1) { 'content-type' => [Array] },
app  |       options: {}
app  |     }
app  |   }
```

from further investigation it seems that the error is caused by this recent update

https://github.com/stackernews/stacker.news/commit/6aac9eeed48215f8fa2f8308b9d1686bd2819cc9#diff-b2aaada1550cebdc06f0f772de2102dcf5c65696d79ecbcc1a0b92e3140bfafcR28-R29

from the lnd api documentation it seems the method still wants the  `dest` and `amt_sat` fields https://api.lightning.community/api/lnd/router/estimate-route-fee/index.html#routerrpcroutefeerequest

**Comment by huumn** [comment]
You need stop/start the docker compose. Lnd got a version bump

**Comment by riccardobl** [comment]
This is what i am doing to make sure the containers are updated
```
bash sndev stop
bash sndev delete
docker compose --env-file .env.development pull
bash sndev start --attach app
```

but i still get the error
