### ISSUE TITLE
TypeError: Cannot read properties of null (reading '4')

### ISSUE THREAD

**Issue by ekzyis** [stackernews/stacker.news#1525]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This is the error that I found in the logs when you visit https://stacker.news/items/743259.

> TypeError: Cannot read properties of null (reading '4')

with stack trace including code from `mathjax`.

Seems like there is a bug in it or how we use it.

### Screenshots

Interestingly, the item is deleted though so not sure what the plugin is trying to parse.

![2024-10-28-183638_1314x105_scrot](https://github.com/user-attachments/assets/b3e9abe2-0a44-4383-b116-196d1fffc79d)

### Steps To Reproduce

1. Go to https://stacker.news/items/743259

### Expected behavior

No error

### Logs

```
Oct 28 17:28:11 ip-172-31-90-3 web: ⨯ TypeError: Cannot read properties of undefined (reading 'bind')
Oct 28 17:28:11 ip-172-31-90-3 web: at NextNodeServer.handleRequestImpl (/var/app/current/node_modules/next/dist/server/base-server.js:475:50)
Oct 28 17:28:11 ip-172-31-90-3 web: at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Oct 28 17:28:11 ip-172-31-90-3 web: Field Query.items took 83ms
Oct 28 17:28:11 ip-172-31-90-3 web: Field Query.hasNewNotes took 118ms
Oct 28 17:28:11 ip-172-31-90-3 web: TypeError: Cannot read properties of null (reading '4')
Oct 28 17:28:11 ip-172-31-90-3 web: at Object.Other [as item] (/var/app/current/node_modules/mathjax-full/js/input/tex/base/BaseConfiguration.js:79:10)
Oct 28 17:28:11 ip-172-31-90-3 web: at SubHandler.parse (/var/app/current/node_modules/mathjax-full/js/input/tex/MapHandler.js:92:39)
Oct 28 17:28:11 ip-172-31-90-3 web: at TexParser.parse (/var/app/current/node_modules/mathjax-full/js/input/tex/TexParser.js:111:54)
Oct 28 17:28:11 ip-172-31-90-3 web: at TexParser.Parse (/var/app/current/node_modules/mathjax-full/js/input/tex/TexParser.js:143:18)
Oct 28 17:28:11 ip-172-31-90-3 web: at new TexParser (/var/app/current/node_modules/mathjax-full/js/input/tex/TexParser.js:76:14)
Oct 28 17:28:11 ip-172-31-90-3 web: at TeX.compile (/var/app/current/node_modules/mathjax-full/js/input/tex.js:118:26)
Oct 28 17:28:11 ip-172-31-90-3 web: at AbstractMathItem.compile (/var/app/current/node_modules/mathjax-full/js/core/MathItem.js:56:39)
Oct 28 17:28:11 ip-172-31-90-3 web: at Object.renderMath (/var/app/current/node_modules/mathjax-full/js/core/MathDocument.js:119:65)
Oct 28 17:28:11 ip-172-31-90-3 web: at RenderList.renderConvert (/var/app/current/node_modules/mathjax-full/js/core/MathDocument.js:171:35)
Oct 28 17:28:11 ip-172-31-90-3 web: at AbstractMathItem.convert (/var/app/current/node_modules/mathjax-full/js/core/MathItem.js:52:32)
Oct 28 17:28:11 ip-172-31-90-3 web: ⨯ TypeError: Cannot read properties of null (reading '4')
Oct 28 17:28:11 ip-172-31-90-3 web: at Object.Other [as item] (/var/app/current/node_modules/mathjax-full/js/input/tex/base/BaseConfiguration.js:79:10)
Oct 28 17:28:11 ip-172-31-90-3 web: at SubHandler.parse (/var/app/current/node_modules/mathjax-full/js/input/tex/MapHandler.js:92:39)
Oct 28 17:28:11 ip-172-31-90-3 web: at TexParser.parse (/var/app/current/node_modules/mathjax-full/js/input/tex/TexParser.js:111:54)
Oct 28 17:28:11 ip-172-31-90-3 web: at TexParser.Parse (/var/app/current/node_modules/mathjax-full/js/input/tex/TexParser.js:143:18)
Oct 28 17:28:11 ip-172-31-90-3 web: at new TexParser (/var/app/current/node_modules/mathjax-full/js/input/tex/TexParser.js:76:14)
Oct 28 17:28:11 ip-172-31-90-3 web: at TeX.compile (/var/app/current/node_modules/mathjax-full/js/input/tex.js:118:26)
Oct 28 17:28:11 ip-172-31-90-3 web: at AbstractMathItem.compile (/var/app/current/node_modules/mathjax-full/js/core/MathItem.js:56:39)
Oct 28 17:28:11 ip-172-31-90-3 web: at Object.renderMath (/var/app/current/node_modules/mathjax-full/js/core/MathDocument.js:119:65)
Oct 28 17:28:11 ip-172-31-90-3 web: at RenderList.renderConvert (/var/app/current/node_modules/mathjax-full/js/core/MathDocument.js:171:35)
Oct 28 17:28:11 ip-172-31-90-3 web: at AbstractMathItem.convert (/var/app/current/node_modules/mathjax-full/js/core/MathItem.js:52:32)
```

### Additional context

- https://stacker.news/items/743010?commentId=743477
- https://stacker.news/items/743010?commentId=743444

**Comment by huumn** [comment]
It might be one of the comments.

**Comment by ekzyis** [comment]
You are right, it's a comment that includes this: `$$₿itcoin.$$`

**Comment by ekzyis** [comment]
Same error was reported here: https://github.com/remarkjs/remark-math/issues/88

**Comment by huumn** [comment]
The move might be to remove certain ranges of unicode characters.

**Comment by huumn** [comment]
It appears to just be the currency block.

**Comment by ekzyis** [comment]
This patch fixes it specifically for [currency symbols](https://www.compart.com/en/unicode/category):

```diff
diff --git a/components/text.js b/components/text.js
index fe70f0a2..4d5087ef 100644
--- a/components/text.js
+++ b/components/text.js
@@ -20,6 +20,7 @@ import rehypeSN from '@/lib/rehype-sn'
 import Embed from './embed'
 import remarkMath from 'remark-math'
 import rehypeMathjax from 'rehype-mathjax'
+import { visit } from 'unist-util-visit'

 const rehypeSNStyled = () => rehypeSN({
   stylers: [{
@@ -33,7 +34,35 @@ const rehypeSNStyled = () => rehypeSN({
   }]
 })

-const remarkPlugins = [gfm, [remarkMath, { singleDollarTextMath: false }]]
+const remarkMathUnicode = () => (tree) => {
+  try {
+    visit(tree, 'paragraph', (node) => {
+      node.children = node.children.map(child => {
+        if (child.type !== 'inlineMath') return child
+
+        // if inline math contains unicode character, rehypeMathjax will throw
+        // see https://github.com/stackernews/stacker.news/issues/1525
+
+        let { hChildren } = child.data
+
+        hChildren = hChildren.map(child2 => {
+          return { ...child2, value: filterUnicode(child2.value) }
+        })
+        child.data.hChildren = hChildren
+
+        return { ...child, value: filterUnicode(child.value) }
+      })
+    })
+  } catch (err) {
+    console.error(err)
+  }
+}
+
+const filterUnicode = text => {
+  return text.replace(/\P{Sc}/u, '')
+}
+
+const remarkPlugins = [gfm, remarkMathUnicode, [remarkMath, { singleDollarTextMath: false }]]
 const rehypePlugins = [rehypeSNStyled, rehypeMathjax]

 export function SearchText ({ text }) {
```

but need to figure out if we need to filter all unicode categories break (probably) and if so, how to match them all since afaict so far, there's no easy way to match all categories after reading [this](https://www.regular-expressions.info/unicode.html).

**Comment by huumn** [comment]
This appears to be fixed in mathjax: https://github.com/mathjax/MathJax/issues/3033

The plugin just uses an outdated version: https://github.com/remarkjs/remark-math/blob/main/packages/rehype-mathjax/package.json

**Comment by huumn** [comment]
We might be able to do an override: https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides

**Comment by huumn** [comment]
Actually it isn't fixed in the `latest` from mathjax (two years old). The maintainer says it'll release in v4.

**Comment by ekzyis** [comment]
There are beta versions of v4 we could try.

**Comment by huumn** [comment]
That might work. rehype-mathjax doesn't do anything too involved so so long as the api hasn't drastically changed it might work.
