### ISSUE TITLE
Seed migration fails on initial build

### ISSUE THREAD

**Issue by aeschylus** [stackernews/stacker.news#178]
## Reproduce
Run `docker-compose up --build` as described in the README. The Postgres db will be created successfully, but the initial seed will fail with:
```
 Prisma schema loaded from prisma/schema.prisma
Running seed from "prisma/seed.js" ...
Result:
PrismaClientKnownRequestError2 [PrismaClientKnownRequestError]:
Invalid `prisma.item.create()` invocation:


  The table `pgboss.job` does not exist in the current database.
    at cb (/app/node_modules/@prisma/client/runtime/index.js:33816:17)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async main (/app/prisma/seed.js:33:3) {
  code: 'P2021',
  clientVersion: '2.25.0',
  meta: { table: 'pgboss.job' }
}
Error: Command failed with exit code 1: node -e "
console.info('Result:')

const __seed = require('./prisma/seed.js')
const __keys = Object.keys(__seed)

async function runSeed() {
  // Execute "seed" named export or default export
  if (__keys && __keys.length) {
    if (__keys.indexOf('seed') !== -1) {
      return __seed.seed()
    } else if (__keys.indexOf('default') !== -1) {
      return __seed.default()
    }
  }
}

runSeed()
  .then(function (result) {
    if (result) {
      console.log(result)
    }
  })
  .catch(function (e) {
    console.error('Error from seed:')
    throw e
  })
```

This is on an M1 mac, which may be part of the issue. However, sn ran locally a few months ago with no issue. I haven't identified the commit where there was a change.

I'm also able to reproduce the above error after the initial build by shelling into the container and running: 
` node_modules/.bin/prisma db seed --preview-feature`

**Comment by ekzyis** [comment]
Can confirm, this also happens on my machine which is not a M1 but a Dell XPS13:

```
$ docker exec -it app /bin/bash
root@eda6487ec012:/app# npx prisma db seed --preview-feature
Prisma schema loaded from prisma/schema.prisma
Running seed from "prisma/seed.js" ...
Result:
PrismaClientKnownRequestError2 [PrismaClientKnownRequestError]: 
Invalid `prisma.item.create()` invocation:


  The table `pgboss.job` does not exist in the current database.
    at cb (/app/node_modules/@prisma/client/runtime/index.js:33816:17)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async main (/app/prisma/seed.js:33:3) {
  code: 'P2021',
  clientVersion: '2.25.0',
  meta: { table: 'pgboss.job' }
}
Error: Command failed with exit code 1: node -e "
console.info('Result:')

const __seed = require('./prisma/seed.js')
const __keys = Object.keys(__seed)

async function runSeed() {
  // Execute "seed" named export or default export
  if (__keys && __keys.length) {
    if (__keys.indexOf('seed') !== -1) {
      return __seed.seed()
    } else if (__keys.indexOf('default') !== -1) {
      return __seed.default()
    }
  }
}

runSeed()
  .then(function (result) {
    if (result) {
      console.log(result)
    }
  })
  .catch(function (e) {
    console.error('Error from seed:')
    throw e
  })
"
```
