### ISSUE TITLE
docker + node 14 on Intel Mac osx crashes

### ISSUE THREAD

**Issue by jowo-io** [stackernews/stacker.news#238]
See the output generated by running the `docker-compose up --build` command as specified in the `README.md`

```
app     | Error: Prisma Migrate has detected that the environment is non-interactive, which is not supported.
app     |
app     | `prisma migrate dev` is an interactive command designed to create new migrations and evolve the database in development.
app     | To apply existing migrations in deployments, use prisma migrate deploy.
app     | See https://www.prisma.io/docs/reference/api-reference/command-reference#migrate-deploy
app     |
app     | > stackernews@0.1.0 dev /app
app     | > NODE_OPTIONS='--trace-warnings' next dev
app     |
app     | ready - started server on 0.0.0.0:3000, url: http://localhost:3000
app     | warn  - You have enabled experimental feature (scrollRestoration) in next.config.js.
app     | warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
app     |
app     | info  - Disabled SWC as replacement for Babel because of custom Babel configuration ".babelrc" https://nextjs.org/docs/messages/swc-disabled
app     | event - compiled client and server successfully in 7.9s (1875 modules)
app     | wait  - compiling /api/graphql (client and server)...
app     | event - compiled successfully in 446 ms (213 modules)
app     | wait  - compiling /404 (client and server)...
app     | wait  - compiling /_error (client and server)...
app     | error - SyntaxError: Unexpected token '||='
app     |     at Object.(api)/./api/resolvers/notifications.js (/app/.next/server/pages/api/graphql.js:330:1)
app     |     at __webpack_require__ (/app/.next/server/webpack-api-runtime.js:33:42)
app     |     at eval (webpack-internal:///(api)/./api/resolvers/index.js:10:72)
app     |     at Object.(api)/./api/resolvers/index.js (/app/.next/server/pages/api/graphql.js:275:1)
app     |     at __webpack_require__ (/app/.next/server/webpack-api-runtime.js:33:42)
app     |     at eval (webpack-internal:///(api)/./pages/api/graphql.js:9:72)
app     |     at Function.__webpack_require__.a (/app/.next/server/webpack-api-runtime.js:97:13)
app     |     at eval (webpack-internal:///(api)/./pages/api/graphql.js:1:21)
app     |     at Object.(api)/./pages/api/graphql.js (/app/.next/server/pages/api/graphql.js:735:1)
app     |     at __webpack_require__ (/app/.next/server/webpack-api-runtime.js:33:42)
app     | error - SyntaxError: Unexpected token '||='
app     |     at Object.(api)/./api/resolvers/notifications.js (/app/.next/server/pages/api/graphql.js:330:1)
app     |     at __webpack_require__ (/app/.next/server/webpack-api-runtime.js:33:42)
app     |     at eval (webpack-internal:///(api)/./api/resolvers/index.js:10:72)
app     |     at Object.(api)/./api/resolvers/index.js (/app/.next/server/pages/api/graphql.js:275:1)
app     |     at __webpack_require__ (/app/.next/server/webpack-api-runtime.js:33:42)
app     |     at eval (webpack-internal:///(api)/./pages/api/graphql.js:9:72)
app     |     at Function.__webpack_require__.a (/app/.next/server/webpack-api-runtime.js:97:13)
app     |     at eval (webpack-internal:///(api)/./pages/api/graphql.js:1:21)
app     |     at Object.(api)/./pages/api/graphql.js (/app/.next/server/pages/api/graphql.js:735:1)
app     |     at __webpack_require__ (/app/.next/server/webpack-api-runtime.js:33:42)
app     | error - SyntaxError: Unexpected token '||='
app     |     at Object.(api)/./api/resolvers/notifications.js (/app/.next/server/pages/api/graphql.js:330:1)
app     |     at __webpack_require__ (/app/.next/server/webpack-api-runtime.js:33:42)
app     |     at eval (webpack-internal:///(api)/./api/resolvers/index.js:10:72)
app     |     at Object.(api)/./api/resolvers/index.js (/app/.next/server/pages/api/graphql.js:275:1)
app     |     at __webpack_require__ (/app/.next/server/webpack-api-runtime.js:33:42)
app     |     at eval (webpack-internal:///(api)/./pages/api/graphql.js:9:72)
app     |     at Function.__webpack_require__.a (/app/.next/server/webpack-api-runtime.js:97:13)
app     |     at eval (webpack-internal:///(api)/./pages/api/graphql.js:1:21)
app     |     at Object.(api)/./pages/api/graphql.js (/app/.next/server/pages/api/graphql.js:735:1)
app     |     at __webpack_require__ (/app/.next/server/webpack-api-runtime.js:33:42)
worker  | working jobs
app     | event - compiled client and server successfully in 1555 ms (1952 modules)
app     | wait  - compiling /recent (client and server)...
app     | warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/basic-features/fast-refresh#how-it-works
app     | event - compiled client and server successfully in 2.7s (2664 modules)
app     | initing prisma
app     | error - unhandledRejection: Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /app/node_modules/sodium-universal/node_modules/sodium-native/prebuilds/linux-x64/node.napi.node)
app     |     at Object.Module._extensions..node (internal/modules/cjs/loader.js:1127:18)
app     |     at Module.load (internal/modules/cjs/loader.js:933:32)
app     |     at Function.Module._load (internal/modules/cjs/loader.js:774:14)
app     |     at Module.require (internal/modules/cjs/loader.js:957:19)
app     |     at require (internal/modules/cjs/helpers.js:88:18)
app     |     at load (/app/node_modules/node-gyp-build/index.js:22:10)
app     |     at Object.<anonymous> (/app/node_modules/sodium-universal/node_modules/sodium-native/index.js:1:39)
app     |     at Module._compile (internal/modules/cjs/loader.js:1068:30)
app     |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
app     |     at Module.load (internal/modules/cjs/loader.js:933:32)
app     | error - SyntaxError: Unexpected token '||='
app     |     at Object.(api)/./api/resolvers/notifications.js (/app/.next/server/pages/api/graphql.js:330:1)
app     |     at __webpack_require__ (/app/.next/server/webpack-api-runtime.js:33:42)
app     |     at eval (webpack-internal:///(api)/./api/resolvers/index.js:10:72)
app     |     at Object.(api)/./api/resolvers/index.js (/app/.next/server/pages/api/graphql.js:275:1)
app     |     at __webpack_require__ (/app/.next/server/webpack-api-runtime.js:33:42)
app     |     at eval (webpack-internal:///(api)/./pages/api/graphql.js:9:72)
app     |     at Function.__webpack_require__.a (/app/.next/server/webpack-api-runtime.js:97:13)
app     |     at eval (webpack-internal:///(api)/./pages/api/graphql.js:1:21)
app     |     at Object.(api)/./pages/api/graphql.js (/app/.next/server/pages/api/graphql.js:735:1)
app     |     at __webpack_require__ (/app/.next/server/webpack-api-runtime.js:33:42)
app     | This package has been deprecated and now it only exports makeExecutableSchema.
app     | And it will no longer receive updates.
app     | We recommend you to migrate to scoped packages such as @graphql-tools/schema, @graphql-tools/utils and etc.
app     | Check out https://www.graphql-tools.com to learn what package you should use instead!
app     | error - Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /app/node_modules/sodium-universal/node_modules/sodium-native/prebuilds/linux-x64/node.napi.node)
app     |     at Object.Module._extensions..node (internal/modules/cjs/loader.js:1127:18)
app     |     at Module.load (internal/modules/cjs/loader.js:933:32)
app     |     at Function.Module._load (internal/modules/cjs/loader.js:774:14)
app     |     at Module.require (internal/modules/cjs/loader.js:957:19)
app     |     at require (internal/modules/cjs/helpers.js:88:18)
app     |     at load (/app/node_modules/node-gyp-build/index.js:22:10)
app     |     at Object.<anonymous> (/app/node_modules/sodium-universal/node_modules/sodium-native/index.js:1:39)
app     |     at Module._compile (internal/modules/cjs/loader.js:1068:30)
app     |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
app     |     at Module.load (internal/modules/cjs/loader.js:933:32) {
app     |   page: '/recent'
app     | }
app     | error - Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /app/node_modules/sodium-universal/node_modules/sodium-native/prebuilds/linux-x64/node.napi.node)
app     |     at Object.Module._extensions..node (internal/modules/cjs/loader.js:1127:18)
app     |     at Module.load (internal/modules/cjs/loader.js:933:32)
app     |     at Function.Module._load (internal/modules/cjs/loader.js:774:14)
app     |     at Module.require (internal/modules/cjs/loader.js:957:19)
app     |     at require (internal/modules/cjs/helpers.js:88:18)
app     |     at load (/app/node_modules/node-gyp-build/index.js:22:10)
app     |     at Object.<anonymous> (/app/node_modules/sodium-universal/node_modules/sodium-native/index.js:1:39)
app     |     at Module._compile (internal/modules/cjs/loader.js:1068:30)
app     |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
app     |     at Module.load (internal/modules/cjs/loader.js:933:32) {
app     |   page: '/recent'
app     | }
app     | error - Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /app/node_modules/sodium-universal/node_modules/sodium-native/prebuilds/linux-x64/node.napi.node)
app     |     at Object.Module._extensions..node (internal/modules/cjs/loader.js:1127:18)
app     |     at Module.load (internal/modules/cjs/loader.js:933:32)
app     |     at Function.Module._load (internal/modules/cjs/loader.js:774:14)
app     |     at Module.require (internal/modules/cjs/loader.js:957:19)
app     |     at require (internal/modules/cjs/helpers.js:88:18)
app     |     at load (/app/node_modules/node-gyp-build/index.js:22:10)
app     |     at Object.<anonymous> (/app/node_modules/sodium-universal/node_modules/sodium-native/index.js:1:39)
app     |     at Module._compile (internal/modules/cjs/loader.js:1068:30)
app     |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
app     |     at Module.load (internal/modules/cjs/loader.js:933:32) {
app     |   page: '/recent'
app     | }
```

Proposed change to the docker file, bumping node version to `16.16.0` (LTS):
<img width="1344" alt="Screenshot 2023-02-18 at 15 56 21" src="https://user-images.githubusercontent.com/12846819/219872535-eab58fd5-528e-408d-99bb-715ca5ff16b2.png">
> Please note, this `node` bump will also bump the `npm` version, which means the `package-lock` file format version will be increased to `v2` and that file will incur a significant change-set.

If this change is unreasonable for some reason, let me know. I haven't used Docker in over 3 years and I'm entirely new to your codebase.
Otherwise let me know and I can open a PR, see branch here: https://github.com/jowo-io/stacker.news/tree/updates-docker-compose-up

**Comment by huumn** [comment]
This was fixed by upgrading to a new image (still on 14) that had a newer glibc: https://github.com/stackernews/stacker.news/pull/249
