### ISSUE TITLE
Local Auth with GitHub failing to create new user

### ISSUE THREAD

**Issue by SatsAllDay** [stackernews/stacker.news#381]
**Description**
When doing local development and trying to sign in with GitHub, I am running into the following error:

```
[next-auth][error][adapter_error_createUser] 
https://next-auth.js.org/errors#adapter_error_createuser 
Invalid `prisma.user.create()` invocation:
{
  data: {
    login: "SatsAllDay",
    ~~~~~
    node_id: "U_kgDOB6yoTA",
    avatar_url: "https://avatars.githubusercontent.com/u/128755788?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/SatsAllDay",
    html_url: "https://github.com/SatsAllDay",
    followers_url: "https://api.github.com/users/SatsAllDay/followers",
    following_url: "https://api.github.com/users/SatsAllDay/following{/other_user}",
    gists_url: "https://api.github.com/users/SatsAllDay/gists{/gist_id}",
    starred_url: "https://api.github.com/users/SatsAllDay/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/SatsAllDay/subscriptions",
    organizations_url: "https://api.github.com/users/SatsAllDay/orgs",
    repos_url: "https://api.github.com/users/SatsAllDay/repos",
    events_url: "https://api.github.com/users/SatsAllDay/events{/privacy}",
    received_events_url: "https://api.github.com/users/SatsAllDay/received_events",
    type: "User",
    site_admin: false,
    name: "SatsAllDay",
    company: null,
    blog: "",
    location: null,
    email: undefined,
    hireable: null,
    bio: "WeAreAllSatoshi on stacker.news",
    twitter_username: null,
    public_repos: 1,
    public_gists: 0,
    followers: 0,
    following: 0,
    created_at: "2023-03-23T22:52:06Z",
    updated_at: "2023-08-07T14:37:12Z",
    emailVerified: null,
?   createdAt?: DateTime,
?   updatedAt?: DateTime,
?   image?: String | Null,
?   msats?: BigInt,
?   freeComments?: Int,
?   freePosts?: Int,
prisma:error 
Invalid `prisma.user.create()` invocation:
{
  data: {
    login: "SatsAllDay",
    ~~~~~
    node_id: "U_kgDOB6yoTA",
    avatar_url: "https://avatars.githubusercontent.com/u/128755788?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/SatsAllDay",
    html_url: "https://github.com/SatsAllDay",
    followers_url: "https://api.github.com/users/SatsAllDay/followers",
    following_url: "https://api.github.com/users/SatsAllDay/following{/other_user}",
    gists_url: "https://api.github.com/users/SatsAllDay/gists{/gist_id}",
    starred_url: "https://api.github.com/users/SatsAllDay/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/SatsAllDay/subscriptions",
    organizations_url: "https://api.github.com/users/SatsAllDay/orgs",
    repos_url: "https://api.github.com/users/SatsAllDay/repos",
    events_url: "https://api.github.com/users/SatsAllDay/events{/privacy}",
    received_events_url: "https://api.github.com/users/SatsAllDay/received_events",
    type: "User",
    site_admin: false,
    name: "SatsAllDay",
    company: null,
    blog: "",
    location: null,
    email: undefined,
    hireable: null,
    bio: "WeAreAllSatoshi on stacker.news",
    twitter_username: null,
    public_repos: 1,
    public_gists: 0,
    followers: 0,
    following: 0,
    created_at: "2023-03-23T22:52:06Z",
    updated_at: "2023-08-07T14:37:12Z",
    emailVerified: null,
?   createdAt?: DateTime,
?   updatedAt?: DateTime,
?   image?: String | Null,
?   msats?: BigInt,
?   freeComments?: Int,
?   freePosts?: Int,
?   checkedNotesAt?: DateTime | Null,
?   pubkey?: String | Null,
?   tipDefault?: Int,
?   tipPopover?: Boolean,
?   upvotePopover?: Boolean,
?   trust?: Float,
?   lastSeenAt?: DateTime | Null,
?   stackedMsats?: BigInt,
?   noteAllDescendants?: Boolean,
?   noteDeposits?: Boolean,
?   noteEarning?: Boolean,
?   noteInvites?: Boolean,
?   noteItemSats?: Boolean,
?   noteMentions?: Boolean,
?   lastCheckedJobs?: DateTime | Null,
?   noteJobIndicator?: Boolean,
?   upvoteTrust?: Float,
?   hideInvoiceDesc?: Boolean,
?   wildWestMode?: Boolean,
?   greeterMode?: Boolean,
?   fiatCurrency?: String,
?   hideFromTopUsers?: Boolean,
?   turboTipping?: Boolean,
?   nostrPubkey?: String | Null,
?   slashtagId?: String | Null,
?   noteCowboyHat?: Boolean,
?   streak?: Int | Null,
?   subs?: UserCreatesubsInput | String[],
?   hideCowboyHat?: Boolean,
?   Bookmarks?: BookmarkCreateNestedManyWithoutUserInput,
?   Donation?: DonationCreateNestedManyWithoutUserInput,
?   Earn?: EarnCreateNestedManyWithoutUserInput,
?   invites?: InviteCreateNestedManyWithoutUserInput,
?   invoices?: InvoiceCreateNestedManyWithoutUserInput,
?   fwdItems?: ItemCreateNestedManyWithoutFwdUserInput,
?   items?: ItemCreateNestedManyWithoutUserInput,
?   actions?: ItemActCreateNestedManyWithoutUserInput,
?   mentions?: MentionCreateNestedManyWithoutUserInput,
?   messages?: MessageCreateNestedManyWithoutUserInput,
?   PollVote?: PollVoteCreateNestedManyWithoutUserInput,
?   PushSubscriptions?: PushSubscriptionCreateNestedManyWithoutUserInput,
?   ReferralAct?: ReferralActCreateNestedManyWithoutReferrerInput,
?   Streak?: StreakCreateNestedManyWithoutUserInput,
?   Subscriptions?: SubscriptionCreateNestedManyWithoutUserInput,
?   ThreadSubscriptions?: ThreadSubscriptionCreateNestedManyWithoutUserInput,
?   Upload?: UploadCreateNestedManyWithoutUserInput,
?   nostrRelays?: UserNostrRelayCreateNestedManyWithoutUserInput,
?   withdrawls?: WithdrawlCreateNestedManyWithoutUserInput,
?   invite?: InviteCreateNestedOneWithoutInviteesInput,
?   photo?: UploadCreateNestedOneWithoutUserInput,
?   referrer?: UserCreateNestedOneWithoutReferreesInput,
?   referrees?: UserCreateNestedManyWithoutReferrerInput,
?   Account?: AccountCreateNestedManyWithoutUserInput,
?   Session?: SessionCreateNestedManyWithoutUserInput
  }
}
Unknown argument `login`. Available options are listed in green.
?   checkedNotesAt?: DateTime | Null,
?   pubkey?: String | Null,
?   tipDefault?: Int,
?   tipPopover?: Boolean,
?   upvotePopover?: Boolean,
?   trust?: Float,
?   lastSeenAt?: DateTime | Null,
?   stackedMsats?: BigInt,
?   noteAllDescendants?: Boolean,
?   noteDeposits?: Boolean,
?   noteEarning?: Boolean,
?   noteInvites?: Boolean,
?   noteItemSats?: Boolean,
?   noteMentions?: Boolean,
?   lastCheckedJobs?: DateTime | Null,
?   noteJobIndicator?: Boolean,
?   upvoteTrust?: Float,
?   hideInvoiceDesc?: Boolean,
?   wildWestMode?: Boolean,
?   greeterMode?: Boolean,
?   fiatCurrency?: String,
?   hideFromTopUsers?: Boolean,
?   turboTipping?: Boolean,
?   nostrPubkey?: String | Null,
?   slashtagId?: String | Null,
?   noteCowboyHat?: Boolean,
?   streak?: Int | Null,
?   subs?: UserCreatesubsInput | String[],
?   hideCowboyHat?: Boolean,
?   Bookmarks?: BookmarkCreateNestedManyWithoutUserInput,
?   Donation?: DonationCreateNestedManyWithoutUserInput,
?   Earn?: EarnCreateNestedManyWithoutUserInput,
?   invites?: InviteCreateNestedManyWithoutUserInput,
?   invoices?: InvoiceCreateNestedManyWithoutUserInput,
?   fwdItems?: ItemCreateNestedManyWithoutFwdUserInput,
?   items?: ItemCreateNestedManyWithoutUserInput,
?   actions?: ItemActCreateNestedManyWithoutUserInput,
?   mentions?: MentionCreateNestedManyWithoutUserInput,
?   messages?: MessageCreateNestedManyWithoutUserInput,
?   PollVote?: PollVoteCreateNestedManyWithoutUserInput,
?   PushSubscriptions?: PushSubscriptionCreateNestedManyWithoutUserInput,
?   ReferralAct?: ReferralActCreateNestedManyWithoutReferrerInput,
?   Streak?: StreakCreateNestedManyWithoutUserInput,
?   Subscriptions?: SubscriptionCreateNestedManyWithoutUserInput,
?   ThreadSubscriptions?: ThreadSubscriptionCreateNestedManyWithoutUserInput,
?   Upload?: UploadCreateNestedManyWithoutUserInput,
?   nostrRelays?: UserNostrRelayCreateNestedManyWithoutUserInput,
?   withdrawls?: WithdrawlCreateNestedManyWithoutUserInput,
?   invite?: InviteCreateNestedOneWithoutInviteesInput,
?   photo?: UploadCreateNestedOneWithoutUserInput,
?   referrer?: UserCreateNestedOneWithoutReferreesInput,
?   referrees?: UserCreateNestedManyWithoutReferrerInput,
?   Account?: AccountCreateNestedManyWithoutUserInput,
?   Session?: SessionCreateNestedManyWithoutUserInput
  }
}
```

**Steps to Reproduce**
1. Spin up local stackernews
2. Setup GitHub OAuth app
3. Attempt to sign in with GitHub (new account)
4. Authorize OAuth app
5. See failure

**Expected behavior**
I expect the user to be created successfully

**Screenshots**
<img width="535" alt="image" src="https://github.com/stackernews/stacker.news/assets/128755788/55da9656-f92e-450f-8ed0-6af2e0c447c1">

**Logs**
See above

**Additional context**

**Comment by huumn** [comment]
Are you on the latest master commit? Did prisma migrate dev run successfully? Docker or metal setup?

I just tried locally and it worked.

**Comment by huumn** [comment]
> Latest as of last night, yes.

Hmm that should be fine. 

The only other thing I can think of is that the docker images use v16.

If you don't mind, try in ./Dockerfile and  ./worker/Dockerfile
```diff
- FROM node:16.16.0-bullseye
+ FROM node:18.17.0-bullseye
```

**Comment by SatsAllDay** [comment]
Same issue :/

**Comment by huumn** [comment]
Does logging in or linking this github account work in prod for you?

**Comment by SatsAllDay** [comment]
I just linked this GitHub account to my existing SN account in prod and yes, it does work.

**Comment by huumn** [comment]
Okay, I'm trying to recreate. It might take me a bit

**Comment by SatsAllDay** [comment]
Some further debugging:

Deleting [this line](https://github.com/stackernews/stacker.news/blob/master/pages/api/auth/%5B...nextauth%5D.js#L133) stopped the existing error from happening, but then resulted in the following error instead:

```
[next-auth][error][OAUTH_PARSE_PROFILE_ERROR] 
https://next-auth.js.org/errors#oauth_parse_profile_error Profile id is missing in GitHub OAuth profile response {
  error: {
    message: 'Profile id is missing in GitHub OAuth profile response',
    stack: 'TypeError: Profile id is missing in GitHub OAuth profile response\n' +
      '    at getProfile (/app/node_modules/next-auth/core/lib/oauth/callback.js:164:28)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
      '    at async oAuthCallback (/app/node_modules/next-auth/core/lib/oauth/callback.js:136:27)\n' +
      '    at async Object.callback (/app/node_modules/next-auth/core/routes/callback.js:52:11)\n' +
      '    at async AuthHandler (/app/node_modules/next-auth/core/index.js:208:28)\n' +
      '    at async NextAuthApiHandler (/app/node_modules/next-auth/next/index.js:22:19)\n' +
      '    at async __WEBPACK_DEFAULT_EXPORT__ (webpack-internal:///(api)/./pages/api/auth/[...nextauth].js:304:3)',
    name: 'TypeError'
  },
  OAuthProfile: {
    login: 'SatsAllDay',
    id: 128755788,
    node_id: 'U_kgDOB6yoTA',
    avatar_url: 'https://avatars.githubusercontent.com/u/128755788?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/SatsAllDay',
    html_url: 'https://github.com/SatsAllDay',
    followers_url: 'https://api.github.com/users/SatsAllDay/followers',
    following_url: 'https://api.github.com/users/SatsAllDay/following{/other_user}',
    gists_url: 'https://api.github.com/users/SatsAllDay/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/SatsAllDay/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/SatsAllDay/subscriptions',
    organizations_url: 'https://api.github.com/users/SatsAllDay/orgs',
    repos_url: 'https://api.github.com/users/SatsAllDay/repos',
    events_url: 'https://api.github.com/users/SatsAllDay/events{/privacy}',
    received_events_url: 'https://api.github.com/users/SatsAllDay/received_events',
    type: 'User',
    site_admin: false,
    name: null,
    company: null,
    blog: '',
    location: null,
    email: null,
    hireable: null,
    bio: 'WeAreAllSatoshi on stacker.news',
    twitter_username: null,
    public_repos: 1,
    public_gists: 0,
    followers: 0,
    following: 0,
    created_at: '2023-03-23T22:52:06Z',
    updated_at: '2023-08-07T14:37:12Z'
  },
  message: 'Profile id is missing in GitHub OAuth profile response'
}
```

So maybe there needs to be some kind of data transformation of the profile info coming from GitHub before going in to the DB, which would make sense according to the earlier prisma error. Though, I don't see why this would only be happening to me.

**Comment by huumn** [comment]
I've been able to recreate it locally. I'm not sure why it doesn't happen outside of the dev env though.

**Comment by SatsAllDay** [comment]
Follow-up to the above...

Making this change:
```diff
- ...profile,
+ id: profile.id,
```
allowed me to log in, JIT-provisioning a new user account.

**Comment by huumn** [comment]
This makes me think this might only happen during new account creation which means this is affecting prod as well

**Comment by SatsAllDay** [comment]
> This makes me think this might only happen during new account creation which means this is affecting prod as well

That is a fair point. I have not tried to create a new account via GitHub OAuth in prod.
