### ISSUE TITLE
ETIMEDOUT messages in logs

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#43]
Getting quite a few of these message in the logs. These could be happening for a number of reasons. They appear to be intermittent and might not be avoidable but there might be a better way to handle it.

```js
Sep 12 16:42:37 ip-172-31-87-148 web: [next-auth][error][client_fetch_error]
Sep 12 16:42:37 ip-172-31-87-148 web: https://next-auth.js.org/errors#client_fetch_error session FetchError: request to https://stacker.news/api/auth/session failed, reason: connect ETIMEDOUT 35.168.134.186:443
Sep 12 16:42:37 ip-172-31-87-148 web: at ClientRequest.<anonymous> (/var/app/current/node_modules/node-fetch/lib/index.js:1461:11)
Sep 12 16:42:37 ip-172-31-87-148 web: at ClientRequest.emit (events.js:376:20)
Sep 12 16:42:37 ip-172-31-87-148 web: at TLSSocket.socketErrorListener (_http_client.js:475:9)
Sep 12 16:42:37 ip-172-31-87-148 web: at TLSSocket.emit (events.js:376:20)
Sep 12 16:42:37 ip-172-31-87-148 web: at emitErrorNT (internal/streams/destroy.js:106:8)
Sep 12 16:42:37 ip-172-31-87-148 web: at emitErrorCloseNT (internal/streams/destroy.js:74:3)
Sep 12 16:42:37 ip-172-31-87-148 web: at processTicksAndRejections (internal/process/task_queues.js:82:21) {
Sep 12 16:42:37 ip-172-31-87-148 web: type: 'system',
Sep 12 16:42:37 ip-172-31-87-148 web: errno: 'ETIMEDOUT',
Sep 12 16:42:37 ip-172-31-87-148 web: code: 'ETIMEDOUT'
Sep 12 16:42:37 ip-172-31-87-148 web: }
```

**Comment by abetusk** [comment]
FWIW, I have a script that polls the RSS feed. I haven't had time to track it down yet, so I haven't made an issue, but I think it fails intermittently. I'm not sure if this is what's causing your `ETIMEDOUT` messages but I thought I'd mention in case they're related.

I'm polling the RSS feed with a simple `wget` of the form:

```
wget -q https://stacker.news/rss -o /dev/null -O -
```

**Comment by huumn** [comment]
I think was related to next-auth which we upgraded. I haven't seen this recently so closing.
