### ISSUE TITLE
worker docker container fails to start in local dev

### ISSUE THREAD

**Issue by SatsAllDay** [stackernews/stacker.news#959]
**Description**
When running the local docker setup, I've found that the worker container fails to start, citing the following issue:
```
node:internal/process/esm_loader:97
    internalBinding('errors').triggerUncaughtException(
                              ^
Error: The package "@esbuild/linux-x64" could not be found, and is needed by esbuild.
If you are installing esbuild with npm, make sure that you don't specify the
"--no-optional" or "--omit=optional" flags. The "optionalDependencies" feature
of "package.json" is used by esbuild to install the correct binary executable
for your current platform.
    at generateBinPath (/app/node_modules/esbuild/lib/main.js:1899:15)
    at esbuildCommandAndArgs (/app/node_modules/esbuild/lib/main.js:1969:33)
    at ensureServiceIsRunning (/app/node_modules/esbuild/lib/main.js:2133:25)
    at startSyncServiceWorker (/app/node_modules/esbuild/lib/main.js:2336:19)
    at Object.<anonymous> (/app/node_modules/esbuild/lib/main.js:2377:3)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
```

**Steps to Reproduce**
`COMPOSE_PROFILES=minimal ./sndev start`

**Expected behavior**
Worker container should start

**Screenshots**
N/A

**Logs**
```
node:internal/process/esm_loader:97
    internalBinding('errors').triggerUncaughtException(
                              ^
Error: The package "@esbuild/linux-x64" could not be found, and is needed by esbuild.
If you are installing esbuild with npm, make sure that you don't specify the
"--no-optional" or "--omit=optional" flags. The "optionalDependencies" feature
of "package.json" is used by esbuild to install the correct binary executable
for your current platform.
    at generateBinPath (/app/node_modules/esbuild/lib/main.js:1899:15)
    at esbuildCommandAndArgs (/app/node_modules/esbuild/lib/main.js:1969:33)
    at ensureServiceIsRunning (/app/node_modules/esbuild/lib/main.js:2133:25)
    at startSyncServiceWorker (/app/node_modules/esbuild/lib/main.js:2336:19)
    at Object.<anonymous> (/app/node_modules/esbuild/lib/main.js:2377:3)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
```

**Environment:**
If you only experience the issue on certain devices or browsers, provide that info.

**Additional context**
I've done some research and the issue appears to be caused by the following. We mount the local copy of `node_modules` into our docker containers. This means we share `node_modules` between our host machine and the docker containers. When one runs `npm install` on the host machine, certain dependencies like `@esbuild` will install based on the host platform. In my case, `darwin` versions are installed, since I am running on macOS on an intel chip. However, since the docker container is based on the linux platform, when you go to invoke certain programs like `worker`, for example, the node runtime will look for different versions of dependencies that are platform dependent.

A hacky solution is to force install the platform-specific version of the package you need for the docker container to work i.e. `npm install --force @esbuild/linux-x64`. This isn't ideal since it adds an entry to `package.json` and requires anyone who runs on a different platform to run `npm install` with `--force` to succeed.

A better solution is probably to install the platform-specific dependency within the docker container. I am trying that out locally.

**Comment by SatsAllDay** [comment]
Here's an update. Putting the following into `docker-compose.override.yml` seems to have fixed the issue:

```yml
version: "3"
services:
  worker:
    command:
      - npm install @esbuild/linux-x64@0.18.20 --no-save --loglevel verbose && npm run worker:dev
```

The diff is
```diff
- npm run worker:dev
+ npm install @esbuild/linux-x64@0.18.20 --no-save --loglevel verbose && npm run worker:dev
```

`--no-save` is critical because this is what omits updating `package.json` and `package-lock.json`, meaning the git tree remains clean.

I can open a PR to make this change into `docker-compose.yml`, if you think that's a good idea @huumn? I assume this is only an issue for developers not using linux locally, so @ekzyis is probably unaffected.

Thoughts? Opinions? Welcome to feedback :)

**Comment by huumn** [comment]
I've encountered this issue too. If you don't run `npm install` locally before running `sndev start` it won't create issues. 

Is there a reason you install on the host before starting the environment? 

The ideal solution here imo is to not share /node_modules with the host, and have npm use a non-standard location for `node_modules` in the app container.

**Comment by SatsAllDay** [comment]
> Is there a reason you install on the host before starting the environment?

Habit, I guess? I suppose it's not required for local development, then? It's definitely an oddity though because `package-lock.json` indicates the `darwin-arm` version of the dependencies, which I assume came from your local install (macOS on apple silicon)?

> The ideal solution here imo is to not share /node_modules with the host, and have npm use a non-standard location for node_modules in the app container.

I can experiment with that. I do think there is an issue with checking in `tsx` though, based on the above regarding having `package-lock.json` include the platform-specific version.

Perhaps we could use `npx tsx@<specific version>` to pin ourselves to the version we're currently using, to remove concern with affecting production, and also not having it represented in `package-lock.json`? I can explore not sharing `node_modules`, too.

**Comment by huumn** [comment]
I think we probably just need to regenerate the package-lock.json if only platform specific packages are being installed.

It appears there's a bug in npm around this: https://github.com/npm/cli/issues/4828

**Comment by SatsAllDay** [comment]
I am trying [this approach](https://stackoverflow.com/a/38601156) which looks promising. I'll report back here with results.
